{% set name = "reportportal-client" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportportal-client-{{ version }}.tar.gz
  sha256: 48bb05b7daf266f0eb5dbb8c7c5debcc257ece404f88a40c472ae61528b23f3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aenum
    - python >=3.6
    - requests >=2.23.0
    - six >=1.15.0

test:
  imports:
    - reportportal_client
    - reportportal_client.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
