{% set name = "reportportal-client" %}
{% set version = "5.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reportportal-client-{{ version }}.tar.gz
  sha256: 9aa153b2ccfe931ecd03847555bfa9f1bc50f3b7c1094d7e6e93cfc198682af6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=40.0
    - setuptools-scm
  run:
    - aenum
    - delayed-assert
    - python >=3.6
    - requests >=2.23.0
    - six >=1.15.0

test:
  imports:
    - reportportal_client
    - reportportal_client.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/client-Python
  summary: Python client for Report Portal v5.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
